/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CorridaRunIdRouteImport } from './routes/corrida.$runId'
import { Route as ApiPublicHooksProduceRouteImport } from './routes/api/public/hooks/produce'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CorridaRunIdRoute = CorridaRunIdRouteImport.update({
  id: '/corrida/$runId',
  path: '/corrida/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksProduceRoute = ApiPublicHooksProduceRouteImport.update({
  id: '/api/public/hooks/produce',
  path: '/api/public/hooks/produce',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/corrida/$runId': typeof CorridaRunIdRoute
  '/api/public/hooks/produce': typeof ApiPublicHooksProduceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/corrida/$runId': typeof CorridaRunIdRoute
  '/api/public/hooks/produce': typeof ApiPublicHooksProduceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/corrida/$runId': typeof CorridaRunIdRoute
  '/api/public/hooks/produce': typeof ApiPublicHooksProduceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/corrida/$runId' | '/api/public/hooks/produce'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/corrida/$runId' | '/api/public/hooks/produce'
  id:
    '__root__' | '/' | '/auth' | '/corrida/$runId' | '/api/public/hooks/produce'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CorridaRunIdRoute: typeof CorridaRunIdRoute
  ApiPublicHooksProduceRoute: typeof ApiPublicHooksProduceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corrida/$runId': {
      id: '/corrida/$runId'
      path: '/corrida/$runId'
      fullPath: '/corrida/$runId'
      preLoaderRoute: typeof CorridaRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/produce': {
      id: '/api/public/hooks/produce'
      path: '/api/public/hooks/produce'
      fullPath: '/api/public/hooks/produce'
      preLoaderRoute: typeof ApiPublicHooksProduceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CorridaRunIdRoute: CorridaRunIdRoute,
  ApiPublicHooksProduceRoute: ApiPublicHooksProduceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
